config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :message, only: [:create]
  
  namespace :account do
    resources :games, except: [:show]
  end

  resources :games, only: :show do 
    resources :playing_sessions, only: [:create, :destroy]
      resources :rpg_characters
      resources :chapters do
        resources :encounters do
          resources :lores
          resources :action_events do
            resources :monsters
            resources :initiatives
            resources :actions
          end
        end
      end
  end
end

app/models/ability.rb
class Ability < ApplicationRecord
  belongs_to :rpg_character
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :action_event
  belongs_to :rpg_character
  belongs_to :dice_roll
end

app/models/action_event.rb
class ActionEvent < ApplicationRecord
  has_many :actions
  has_many :initiatives
  has_many :monsters
  belongs_to :encounter
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :game
  has_many :encounters
end

app/models/dice.rb
class Dice < ApplicationRecord
  has_many :dice_rolls
end

app/models/dice_roll.rb
class DiceRoll < ApplicationRecord
  belongs_to :dice
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  has_many :action_events
  has_many :lores
  belongs_to :chapter
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :rpg_character
end

app/models/feature_trait.rb
class FeatureTrait < ApplicationRecord
  belongs_to :rpg_character
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  
  has_many :chapters
  has_many :messages
  has_many :playing_sessions
  has_many :rpg_characters
  has_many :users, through: :playing_sessions
  belongs_to :gm, class_name: "User" #, foreign_key: "gm_id"
  belongs_to :creator, class_name: "User"
end

app/models/initiative.rb
class Initiative < ApplicationRecord
  belongs_to :dice_roll
  belongs_to :action_event
  belongs_to :rpg_character
  belongs_to :monster
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :rpg_character
end

app/models/lore.rb
class Lore < ApplicationRecord
  belongs_to :encounter
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
  
  belongs_to :user
  belongs_to :game
end

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :action_event
end

app/models/proficiency.rb
class Proficiency < ApplicationRecord
  belongs_to :rpg_character
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :rpg_character
end

app/models/spell_attack.rb
class SpellAttack < ApplicationRecord
  belongs_to :rpg_character
  belongs_to :dice
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_username
  has_many :playing_sessions
  has_many :games, through: :playing_sessions
  has_many :rpg_characters
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, 
  :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def set_username
    self.username = "#{first_name}_#{last_name}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-header">
  <h1>Tabletopr</h1>
  <div class="home-tab">
    <h2>All games:</h2>
  </div>
</div>
<div class="games">
  <% @games.each do |game| %>
  <div class="game-item">
    <% if game[:photo].nil? %>
    <div class="game-background-item" style="background-image: linear-gradient(90deg, rgba(1, 1, 1, 0) 1%, white 99%),
    url('<%= image_path 'background.jpg' %>')"></div>
    <% else %>
    <div class="game-background-item" style="background-image: linear-gradient(90deg, rgba(1, 1, 1, 0) 1%, white 99%),
    url('<%= cl_image_path game.photo %>')"></div>
    <% end %>
    <div class="game-item-wrapper">
      <div class="game-item-content">
        <%= link_to game_path(game) do %>
        <h2>
          <%= game.name %>
        </h2>
        <% end -%>
        <p>
          <%= game.description %>
        </p>
      </div>
      <div class="game-item-actions">
        <% if user_signed_in? %>

        <% if current_user.games.include?(game) %>
        <%= link_to game_path(game), class: "view-game full-height" do %>
        <i class="fa fa-eye fa-2x"></i>
        <% end -%>
        <% else %>
        <%= link_to game_path(game), class: "view-game half-height" do %>
        <i class="fa fa-eye fa-2x"></i>
        <% end -%>
        <div class="join-game">
          <%= simple_form_for [game, @playing_session] do |f|  %>
          <%= f.submit "join", id: "join-game-submit" %>
          <i class="fa fa-plus fa-2x"></i>
          <% end -%>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <div class="fa fa-compass fa-2x"></div>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Notification -->


    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <div class="badge-container" data-toggle="dropdown">
          <i class="fa fa-map"></i>
          <!-- ADD SOMETHING TO DISPLAY ACTIVITY HERE -->
          <div class="badge badge-red"><%= current_user.games.count %></div>
        </div>
        <% unless current_user.games.count == 0 %>
        
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% current_user.games.each do |game| %>
          <li>
            <%= link_to game.name, game_path(game) %>
          </li>
          <% end %>
        </ul>
        <% end %>
      </div>
    </div>
    <div class="dropdown">
      <div class="image-link dropdown-toggle" data-toggle="dropdown">
        <%= image_tag current_user.facebook_picture_url, class: "account-link", id: "navbar-wagon-menu" %>
        <div class="gradient"></div>
      </div>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "#" do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to root_path do %>
          <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "#" do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to root_path do %>
          <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>