config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :message, only: [:create]
  
  namespace :account do
    resources :games, except: [:show]
  end

  resources :games, only: :show do 
    resources :playing_sessions, only: [:create, :destroy]
      resources :rpg_characters
      resources :chapters do
        resources :encounters do
          resources :lores
          resources :action_events do
            resources :monsters
            resources :initiatives
            resources :actions
          end
        end
      end
  end
end

app/models/ability.rb
class Ability < ApplicationRecord
  belongs_to :rpg_character
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :action_event
  belongs_to :rpg_character
  belongs_to :dice_roll
end

app/models/action_event.rb
class ActionEvent < ApplicationRecord
  has_many :actions
  has_many :initiatives
  has_many :monsters
  belongs_to :encounter
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :game
  has_many :encounters
end

app/models/dice.rb
class Dice < ApplicationRecord
  has_many :dice_rolls
end

app/models/dice_roll.rb
class DiceRoll < ApplicationRecord
  belongs_to :dice
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  has_many :action_events
  has_many :lores
  belongs_to :chapter
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :rpg_character
end

app/models/feature_trait.rb
class FeatureTrait < ApplicationRecord
  belongs_to :rpg_character
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  
  has_many :chapters
  has_many :messages
  has_many :playing_sessions
  has_many :rpg_characters
  has_many :users, through: :playing_sessions
  belongs_to :gm, class_name: "User" #, foreign_key: "gm_id"
  belongs_to :creator, class_name: "User"
end

app/models/initiative.rb
class Initiative < ApplicationRecord
  belongs_to :dice_roll
  belongs_to :action_event
  belongs_to :rpg_character
  belongs_to :monster
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :rpg_character
end

app/models/lore.rb
class Lore < ApplicationRecord
  belongs_to :encounter
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
  
  belongs_to :user
  belongs_to :game
end

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :action_event
end

app/models/proficiency.rb
class Proficiency < ApplicationRecord
  belongs_to :rpg_character
end

app/models/rpg_character.rb
class RpgCharacter < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :abilities
  has_many :actions
  has_many :equipments
  has_many :feature_traits
  has_many :languages
  has_many :proficiencies
  belongs_to :user
  belongs_to :game
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :rpg_character
end

app/models/spell_attack.rb
class SpellAttack < ApplicationRecord
  belongs_to :rpg_character
  belongs_to :dice
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_username
  has_many :playing_sessions
  has_many :games, through: :playing_sessions
  has_many :rpg_characters
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, 
  :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def set_username
    self.username = "#{first_name}_#{last_name}"
  end
end

app/controllers/account/games_controller.rb
class Account::GamesController < ApplicationController
  before_action :set_game, only: [:edit, :update, :destroy]
  def index
  end

  def new
    @game = Game.new
  end

  def create
    game = Game.new(game_params)
    game.creator = current_user
    game.gm = current_user
    if game.save!
      redirect_to game_path(game)
    else
      render 'new'
    end
  end

  def edit
    @players = set_players
  end

  def update
    if @game.update(game_params)
      redirect_to game_path(@game)
      flash[:notice] = "Succesfully updated game"
    else
      render 'new'
    end
  end

  def destroy
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def set_players
    result = []
    @game.creator == @game.gm ? result << @game.creator : result << @game.gm << @game.creator
    @game.users.each do |user|
      result << user unless result.include?(user)
    end
    result
  end

  def game_params
    result = params.require(:game).permit(:name, :description, :photo, :photo_cache)
    result[:gm_id] = params[:gm_id]
    result
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game

  def show
    @playing_session = @game.playing_sessions.where(user: current_user).first || PlayingSession.new
    @current_chapter = @game.chapters.last
    @messages = @game.messages.order(created_at: :desc)
    @character = RpgCharacter.where(user: current_user, game: @game).first
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_chapter.html.erb
 <div class="chapters">
      <% unless @current_chapter.nil? %>

      <div class="current_chapter">
        <h2>
          <%= @current_chapter.title %>
        </h2>
        <p>
          <%= @current_chapter.description %>
        </p>
        <div class="encounters">
          <% @current_chapter.encounters.each do |encounter| %>
          <div class="encounter">
            <%= encounter.description %>
          </div>
          <div class="action-events">
            <% encounter.action_events.each do |action_event| %>
            <%= action_event.description %>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>

app/views/games/_chat.html.erb
<div class="chat">
  <div class="messages" id="messages">
  <% if @messages == [] %>
    <p class="chat-placeholder">
      No messages yet
    </p>
  <% end %>
    <%= render @messages %>
  </div>
  <div class="chat-submit">
    <form> 
      <input type="text" class="chat-input" data-behavior="room_speaker"> 
      <input type="hidden" value="<%= current_user.id %>" id="message_user" data-behavior="room_speaker">
      <input type="hidden" value="<%= @game.id %>" id="message_game" data-behavior="room_speaker">
      <input type="submit" class="btn btn-primary">
    </form>
  </div>
</div>

app/views/games/_game.html.erb
<div class="container">
  <div class="header-info">
    <div class="row">
      <% if @character %>
      <div class="col-xs-12 col-lg-6">

        <div class="character">
          <%= link_to game_rpg_character_path(@game, @character) do %>
          <h3>
            <%= @character.name %>
          </h3>
          <% end -%>
          <div class="decoration">
            <div class="shape-left"></div>
            <div class="shape-right"></div>
          </div>
          <%= link_to game_rpg_character_path(@game, @character) do %>
          <% if @character.picture_url %>
          <%= cl_image_tag(@character.picture_url,
          width: 150, height: 150, crop: :fill, class: "avatar-xlarge") %>
          <% else %>
          <%= image_tag 'character_placeholder.jpg', class: "avatar-xlarge" %>
          <% end %>
          <% end -%>
        </div>
      </div>
      <% end %>
      <div class="col-xs-12 col-lg-6">
        <div class="game">
          <h2>
            <%= @game.name %>
          </h2>
          <p class="game-description">
            <%= @game.description %>
          </p>
          <div class="collapse-menu-items">
            <a class="btn btn-primary" role="button" data-toggle="collapse" href="#collapseUsers" aria-expanded="false" aria-controls="collapseUsers">
              Users
            </a>
            <a class="btn btn-primary" role="button" data-toggle="collapse" href="#collapseActions" aria-expanded="false" aria-controls="collapseActions">
              Actions
            </a>
            <a class="btn btn-primary" role="button" data-toggle="collapse" href="#collapseViews" aria-expanded="false" aria-controls="collapseViews">
              View
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="accordion-content">
  <div class="collapse" id="collapseViews">
    <div class="well">
     <%= link_to "all chapters", game_chapters_path(@game)  %>
     <% if @character %>
     <%= link_to "character", game_rpg_character_path(@game, @character)  %>
     <% end %>
   </div>
 </div>
 <div class="collapse" id="collapseUsers">
  <div class="well">
    <div class="game-users">
      <div class="row">
        <% @game.users.each do |user| %>
        <div class="col-xs-3 col-lg-2">
          <div class="game-user">
            <%= image_tag user.facebook_picture_url %>
            <p>
              <%= user.first_name %>
            </p>
          </div>
        </div>
        <% end %>
      </div> 
    </div>
  </div>
</div>
<div class="collapse" id="collapseActions">
  <div class="well">
   <div class="game-joined">
    <% if current_user.games.include?(@game) %>
    <p>
      You have joined this game
    </p>
    <%= link_to "Leave?", game_playing_session_path(@game, @playing_session), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
    <%= link_to "new chapter", new_game_chapter_path(@game), class:"btn btn-primary"  %>
    <%= link_to edit_account_game_path, class: "btn btn-primary" do %>
    <i class="fa fa-edit"></i>
    <% end -%>
    <% if @character.nil? %>
    <%= link_to "Create character", new_game_rpg_character_path(@game), class: "btn btn-primary" %>
    <% else %>
    <%= link_to "Edit character", edit_game_rpg_character_path(@character), class: "btn btn-primary" %>
    <% end %>
    <% else %>
    <p>
      You have not joined this game
    </p>
    <%= simple_form_for [@game, @playing_session] do |f|  %>
    <%= f.submit "Join this game", class:"btn btn-primary" %>
    <% end -%>
    <% end %>
  </div>
</div>
</div>
</div>

<%= render 'chapter' %>

app/views/games/show.html.erb
<% if @game[:photo].nil? %>
<div class="header" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
url('<%= image_path 'background.jpg' %>')"></div>
<% else %>
<div class="header" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
url('<%= cl_image_path @game.photo %>')"></div>
<% end %>
<div class="hidden" id="current_user_id"><%= current_user.id %></div>
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-lg-8">
      <%= render 'game' %>
    </div>
    <div class="col-xs-12 col-lg-4">
      <%= render 'chat' %>
    </div>
  </div>
</div>
<%= link_to "#", id:"toggle-chat" do %>
<i class="fa fa-comment-o"></i>
<% end -%>